FROM docker.io/bitnami/airflow-worker:2.0.1
LABEL maintainer "Gemeente Amsterdam <datapunt@amsterdam.nl>"

ARG AIRFLOW_USER_HOME=/usr/local/airflow
ENV AIRFLOW_USER_HOME=${AIRFLOW_USER_HOME}
ENV AIRFLOW_HOME=${AIRFLOW_USER_HOME}

USER root
RUN apt-get update \
 && apt-get dist-upgrade -y \
 && apt-get autoremove -y \
 && apt-get install --no-install-recommends -y \
        unzip \
        gcc \
        libc-dev \
        libpq-dev \
        wget \
        dnsutils \
        vim-tiny \
        net-tools \
        netcat \
        libgeos-3.7 \
        gdal-bin \
        postgresql-client-11 \
        libgdal20 \
        libspatialite7 \
        libfreexl1 \
        libgeotiff2 \
        libwebp6 \
        proj-bin \
        mime-support \
        gettext \
        libwebpmux3 \
        libwebpdemux2 \
        libxml2 \
        libfreetype6 \
        libtiff5 \
        rsync \
        libaio1 \
        supervisor \
        curl \
        libcurl4 \
        zip \
  && rm -rf /var/lib/apt/lists/* /var/cache/debconf/*-old

COPY scripts/mkvars.py ${AIRFLOW_USER_HOME}/scripts/mkvars.py
COPY scripts/mkuser.py ${AIRFLOW_USER_HOME}/scripts/mkuser.py
# COPY scripts/checkdags.py ${AIRFLOW_USER_HOME}/scripts/checkdags.py
COPY data/ ${AIRFLOW_USER_HOME}/data/
COPY vars ${AIRFLOW_USER_HOME}/vars/
COPY vsd ${AIRFLOW_USER_HOME}/vsd/
# this copy is used to make sure the VSD dag (.py) gets loaded correctly
# Airflow is complaining about missing the files in the path below
# TODO figure out why, seems that vsd .py file is in /opt/bitnami/airflow/dags/git_dags/
# and it's looking in the code for the /vsd/ folder one level up (parent). So it is looking
# in /opt/bitnami/airflow/dags/vsd/ instead of ${AIRFLOW_USER_HOME}/vsd/
COPY vsd /opt/bitnami/airflow/dags/vsd/
COPY scripts/run.sh /run.sh

COPY requirements* ./
ARG PIP_REQUIREMENTS=requirements.txt
RUN . /opt/bitnami/airflow/venv/bin/activate && pip install --no-cache-dir -r $PIP_REQUIREMENTS
RUN /opt/bitnami/airflow/venv/bin/python ${AIRFLOW_USER_HOME}/scripts/mkvars.py

USER 1001
WORKDIR ${AIRFLOW_USER_HOME}

EXPOSE 8080

ENTRYPOINT [ "/opt/bitnami/scripts/airflow-worker/entrypoint.sh" ]
CMD [ "/run.sh", "worker" ]
