FROM docker.io/bitnami/airflow:2.0.1
LABEL maintainer "Gemeente Amsterdam <datapunt@amsterdam.nl>"

USER root
RUN apt-get update \
 && apt-get dist-upgrade -y \
 && apt-get autoremove -y \
 && apt-get install --no-install-recommends -y \
        unzip \
        gcc \
        libc-dev \
        libpq-dev \
        wget \
        dnsutils \
        vim-tiny \
        net-tools \
        netcat \
        libgeos-3.7 \
        gdal-bin \
        postgresql-client-11 \
        libgdal20 \
        libspatialite7 \
        libfreexl1 \
        libgeotiff2 \
        libwebp6 \
        proj-bin \
        mime-support \
        gettext \
        libwebpmux3 \
        libwebpdemux2 \
        libxml2 \
        libfreetype6 \
        libtiff5 \
        rsync \
        libaio1 \
        supervisor \
        curl \
        libcurl4 \
        zip \
  && rm -rf /var/lib/apt/lists/* /var/cache/debconf/*-old

COPY scripts/mkvars.py ${AIRFLOW_USER_HOME}/scripts/mkvars.py
COPY scripts/mkuser.py ${AIRFLOW_USER_HOME}/scripts/mkuser.py
# COPY scripts/checkdags.py ${AIRFLOW_USER_HOME}/scripts/checkdags.py
COPY data/ ${AIRFLOW_USER_HOME}/data/
COPY vars ${AIRFLOW_USER_HOME}/vars/
COPY scripts/run.sh /run.sh

USER 1001

COPY requirements* ./
ARG PIP_REQUIREMENTS=requirements.txt
RUN /opt/bitnami/airflow/venv/bin/pip install --no-cache-dir -r $PIP_REQUIREMENTS

EXPOSE 8080

ENTRYPOINT [ "/opt/bitnami/scripts/airflow/entrypoint.sh" ]
CMD [ "/run.sh", "webserver" ]