version: "3.7"
services:

  database:
    image: amsterdam/postgres11
    ports:
      - "5417:5432"
    environment:
      POSTGRES_DB: ds_airflow
      POSTGRES_USER: ds_airflow
      POSTGRES_PASSWORD: insecure

  dso_database:
    image: amsterdam/postgres11
    ports:
      - "5416:5432"
    environment:
      POSTGRES_DB: dataservices
      POSTGRES_USER: dataservices
      POSTGRES_PASSWORD: insecure
    extra_hosts:
      admin.data.amsterdam.nl: 10.243.16.4

  airflow:
    build:
      context: .
      dockerfile: Dockerfile-worker
    environment:
      AIRFLOW_CONN_POSTGRES_DEFAULT:
        "postgresql://dataservices:insecure@dso_database:5432\
        /dataservices?cursor=dictcursor&"
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: "postgresql://ds_airflow:insecure@database:5432/ds_airflow"
      AIRFLOW_CONN_ORACLE_DWH_STADSDELEN:
        "oracle://oracle_user:insecure@localhost:1521/SID001?encoding=UTF-8&nencoding=UTF-8"
      SCHEMA_URL:  "https://schemas.data.amsterdam.nl/datasets/"
      SLACK_WEBHOOK: "https://api.data.amsterdam.nl/nowhere"
    volumes:
      - ./dags:/opt/bitnami/airflow/dags
      - ./plugins:/opt/bitnami/airflow/plugins
