FROM docker.io/bitnami/airflow-scheduler:2.0.1-debian-10-r8
LABEL maintainer "Gemeente Amsterdam <datapunt@amsterdam.nl>"

USER root
RUN apt-get update \
 && apt-get dist-upgrade -y \
 && apt-get autoremove -y \
 && apt-get install --no-install-recommends -y \
        unzip \
        gcc \
        libc-dev \
        wget \
        dnsutils \
        vim-tiny \
        net-tools \
        netcat \
        libgeos-3.7 \
        gdal-bin \
        postgresql-client-11 \
        libgdal20 \
        libspatialite7 \
        libfreexl1 \
        libgeotiff2 \
        libwebp6 \
        proj-bin \
        mime-support \
        gettext \
        libwebpmux3 \
        libwebpdemux2 \
        libxml2 \
        libfreetype6 \
        libtiff5 \
  && rm -rf /var/lib/apt/lists/* /var/cache/debconf/*-old

EXPOSE 8080

USER 1001

COPY requirements* ./
ARG PIP_REQUIREMENTS=requirements.txt
RUN . /opt/bitnami/airflow/venv/bin/activate && pip install --no-cache-dir -r $PIP_REQUIREMENTS

ENTRYPOINT [ "/app-entrypoint.sh" ]
CMD [ "/run.sh" ]
